// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Grid(): $CancellablePromise<(($models.Sprite | null)[] | null)[] | null> {
    return $Call.ByID(2127874272);
}

export function MagicLeft(): $CancellablePromise<void> {
    return $Call.ByID(1925835130);
}

export function MagicRight(): $CancellablePromise<void> {
    return $Call.ByID(3319786823);
}

export function MoveLeft(): $CancellablePromise<boolean> {
    return $Call.ByID(383433528);
}

export function MoveRight(): $CancellablePromise<boolean> {
    return $Call.ByID(1999623053);
}
