// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as common$0 from "../common/models.js";

/**
 * Chapter represents the number of levels in a chapter.
 */
export type Chapter = number;

export interface Sprite {
    "Cell": common$0.Cell;
}
