// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

export function Base64Decode(input: string): $CancellablePromise<string> {
    return $Call.ByID(4119418432, input);
}

export function Base64Encode(input: string): $CancellablePromise<string> {
    return $Call.ByID(2278369876, input);
}

export function HTMLDecode(input: string): $CancellablePromise<string> {
    return $Call.ByID(3450012150, input);
}

export function HTMLEncode(input: string): $CancellablePromise<string> {
    return $Call.ByID(2859933054, input);
}

export function URLDecode(input: string): $CancellablePromise<string> {
    return $Call.ByID(4044000620, input);
}

export function URLEncode(input: string): $CancellablePromise<string> {
    return $Call.ByID(628365712, input);
}
