// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

export function D2(data: string): $CancellablePromise<string> {
    return $Call.ByID(3547150142, data);
}

export function Ndor(input: string): $CancellablePromise<string> {
    return $Call.ByID(2609509691, input);
}
