// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

export function Html(data: string): $CancellablePromise<string> {
    return $Call.ByID(1255849589, data);
}

export function Json(data: string): $CancellablePromise<string> {
    return $Call.ByID(1647851362, data);
}

export function Toml(data: string): $CancellablePromise<string> {
    return $Call.ByID(1653295408, data);
}

export function Yaml(data: string): $CancellablePromise<string> {
    return $Call.ByID(2296061631, data);
}
