// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Cell {
    "Images": string[] | null;
    "BorderTop": boolean;
    "BorderBottom": boolean;
    "BorderLeft": boolean;
    "BorderRight": boolean;
}
