// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

export function Json2Toml(data: string): $CancellablePromise<string> {
    return $Call.ByID(1710518952, data);
}

export function Json2Yaml(data: string): $CancellablePromise<string> {
    return $Call.ByID(2793242359, data);
}

export function Toml2Json(data: string): $CancellablePromise<string> {
    return $Call.ByID(871597048, data);
}

export function Toml2Yaml(data: string): $CancellablePromise<string> {
    return $Call.ByID(3236081181, data);
}

export function Yaml2Json(data: string): $CancellablePromise<string> {
    return $Call.ByID(2854281405, data);
}

export function Yaml2Toml(data: string): $CancellablePromise<string> {
    return $Call.ByID(4131770875, data);
}
