// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

export function Json2Toml(data: string): $CancellablePromise<string> {
    return $Call.ByID(1619034867, data);
}

export function Json2Yaml(data: string): $CancellablePromise<string> {
    return $Call.ByID(2247453176, data);
}

export function Toml2Json(data: string): $CancellablePromise<string> {
    return $Call.ByID(2872147207, data);
}

export function Toml2Yaml(data: string): $CancellablePromise<string> {
    return $Call.ByID(3503250274, data);
}

export function Yaml2Json(data: string): $CancellablePromise<string> {
    return $Call.ByID(132096138, data);
}

export function Yaml2Toml(data: string): $CancellablePromise<string> {
    return $Call.ByID(3249865560, data);
}
