// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

export function Base64Decode(input: string): $CancellablePromise<string> {
    return $Call.ByID(1593701683, input);
}

export function Base64Encode(input: string): $CancellablePromise<string> {
    return $Call.ByID(1126958715, input);
}

export function HTMLDecode(input: string): $CancellablePromise<string> {
    return $Call.ByID(1673334453, input);
}

export function HTMLEncode(input: string): $CancellablePromise<string> {
    return $Call.ByID(2059452641, input);
}

export function URLDecode(input: string): $CancellablePromise<string> {
    return $Call.ByID(4234813465, input);
}

export function URLEncode(input: string): $CancellablePromise<string> {
    return $Call.ByID(3164389733, input);
}
