// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

export function AsciiArt(input: string, font: string): $CancellablePromise<string> {
    return $Call.ByID(343530981, input, font);
}

export function Hash(input: string): $CancellablePromise<{ [_ in string]?: string } | null> {
    return $Call.ByID(2197541025, input);
}
