// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

export function Json(data: string): $CancellablePromise<string> {
    return $Call.ByID(3090650873, data);
}

export function Toml(data: string): $CancellablePromise<string> {
    return $Call.ByID(2573874263, data);
}

export function Yaml(data: string): $CancellablePromise<string> {
    return $Call.ByID(619218492, data);
}
