// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConvertJsonToToml(arg1) {
  return window['go']['main']['App']['ConvertJsonToToml'](arg1);
}

export function ConvertJsonToYaml(arg1) {
  return window['go']['main']['App']['ConvertJsonToYaml'](arg1);
}

export function ConvertTomlToJson(arg1) {
  return window['go']['main']['App']['ConvertTomlToJson'](arg1);
}

export function ConvertTomlToYaml(arg1) {
  return window['go']['main']['App']['ConvertTomlToYaml'](arg1);
}

export function ConvertYamlToJson(arg1) {
  return window['go']['main']['App']['ConvertYamlToJson'](arg1);
}

export function ConvertYamlToToml(arg1) {
  return window['go']['main']['App']['ConvertYamlToToml'](arg1);
}

export function FormatHtml(arg1) {
  return window['go']['main']['App']['FormatHtml'](arg1);
}

export function FormatJson(arg1) {
  return window['go']['main']['App']['FormatJson'](arg1);
}

export function FormatToml(arg1) {
  return window['go']['main']['App']['FormatToml'](arg1);
}

export function FormatYaml(arg1) {
  return window['go']['main']['App']['FormatYaml'](arg1);
}
