// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConvertJsonToToml(arg1:string):Promise<string>;

export function ConvertJsonToYaml(arg1:string):Promise<string>;

export function ConvertTomlToJson(arg1:string):Promise<string>;

export function ConvertTomlToYaml(arg1:string):Promise<string>;

export function ConvertYamlToJson(arg1:string):Promise<string>;

export function ConvertYamlToToml(arg1:string):Promise<string>;

export function FormatHtml(arg1:string):Promise<string>;

export function FormatJson(arg1:string):Promise<string>;

export function FormatToml(arg1:string):Promise<string>;

export function FormatYaml(arg1:string):Promise<string>;
