// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

export function AsciiArt(input: string, font: string): $CancellablePromise<string> {
    return $Call.ByID(3382139641, input, font);
}

export function D2Svg(data: string): $CancellablePromise<string> {
    return $Call.ByID(4014805499, data);
}

export function Hash(input: string): $CancellablePromise<{ [_ in string]?: string } | null> {
    return $Call.ByID(4197481629, input);
}

export function Json2Svg(data: string): $CancellablePromise<string> {
    return $Call.ByID(3754905499, data);
}

export function NdorPng(input: string): $CancellablePromise<string> {
    return $Call.ByID(3612999669, input);
}

export function Toml2Svg(data: string): $CancellablePromise<string> {
    return $Call.ByID(2199400813, data);
}

export function Yaml2Svg(data: string): $CancellablePromise<string> {
    return $Call.ByID(230402614, data);
}
