// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

export function ConvertJsonToToml(input: string): $CancellablePromise<string> {
    return $Call.ByID(2837957667, input);
}

export function ConvertJsonToYaml(input: string): $CancellablePromise<string> {
    return $Call.ByID(2488354344, input);
}

export function ConvertTomlToJson(input: string): $CancellablePromise<string> {
    return $Call.ByID(1662259047, input);
}

export function ConvertTomlToYaml(input: string): $CancellablePromise<string> {
    return $Call.ByID(2293362114, input);
}

export function ConvertYamlToJson(input: string): $CancellablePromise<string> {
    return $Call.ByID(3002591812, input);
}

export function ConvertYamlToToml(input: string): $CancellablePromise<string> {
    return $Call.ByID(23634670, input);
}

export function FormatHtml(input: string): $CancellablePromise<string> {
    return $Call.ByID(2936911431, input);
}

export function FormatJson(input: string): $CancellablePromise<string> {
    return $Call.ByID(1329261636, input);
}

export function FormatToml(input: string): $CancellablePromise<string> {
    return $Call.ByID(2645271790, input);
}

export function FormatYaml(input: string): $CancellablePromise<string> {
    return $Call.ByID(422456457, input);
}

export function GenJsonSvg(input: string): $CancellablePromise<string> {
    return $Call.ByID(760749191, input);
}

export function GenTomlSvg(input: string): $CancellablePromise<string> {
    return $Call.ByID(122256601, input);
}

export function GenYamlSvg(input: string): $CancellablePromise<string> {
    return $Call.ByID(2197162996, input);
}
